<?php
/**
 *
 * Matomo Analytics extension for the phpBB Forum Software package.
 *
 * @copyright (c) 2014 phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
    exit;
}

if (empty($lang) || !is_array($lang))
{
    $lang = [];
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, [
    'PHPBB_ANALYTICS_PRIVACY_POLICY' => '
        <br><br>
        <h3>Analytics</h3>
        “%1$s” may use MAtomo Analytics, a web analytics service provided by  InnoCraft Limited (InnoCraft, we), to help us understand how visitors use the site. Matomo uses cookies and similar technologies to collect information about your interactions with the site, including the pages you visit, the time spent on each page, and general usage patterns.
        <br><br>
        The information generated by these cookies about your use of “%1$s” (may include your IP address) is transmitted to and stored on the Matomo deployement solution choosed by the website owned (might be on premise, or into cloud solution). The website owner uses this information to evaluate your use of the site, compile reports on website activity, the uses of thoses infornation is decided by the website owner.
        <br><br>
        Thoses informations may be transfer to a third parties. To learn more about how the statistics informations are used, contact the website owner.
        <br><br>
        If you want to opt out of the statistics collection <div id="matomo-opt-out"></div><script src="%1$s/index.php?module=CoreAdminHome&action=optOutJS&div=matomo-opt-out></script>.
    ',
]);
