services:
    cube.matomoanalytics.listener:
        class: cube\matomoanalytics\event\listener
        arguments:
            - '@config'
            - '@language'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
